---
version: 2.1

orbs:
  node: circleci/node@5

executors:
  node:
    docker:
      - image: amazon/dynamodb-local:1.22.0

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/beyonce
    executor: node
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
          include-branch-in-cache-key: false
      - run:
          name: build
          command: yarn run build
      - run:
          name: test
          command: yarn test
