---
version: 2.1

orbs:
  node: circleci/node@5

executors:
  node:
    docker:
      # Note: this is deprecated with no replacement:
      # https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034#deprecated-images-3
      - image: circleci/dynamodb:11-jdk-oracle

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/beyonce
    executor: node
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
          include-branch-in-cache-key: false
      - run:
          name: build
          command: yarn run build
      - run:
          name: test
          command: yarn test
