---
version: 2.1

executors:
  node:
    docker:
      - image: circleci/dynamodb:11-jdk-oracle

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/beyonce
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          include-branch-in-cache-key: false
      - run:
          name: build
          command: yarn run build
      - run:
          name: test
          command: yarn run test --maxWorkers=2
